### ISSUE TITLE
KeyError: '3d'

### ISSUE THREAD

**Issue by picpic020960** [codetoday-london/simulation-3d-solar-system-in-python-using-matplotlib#1]
Bonjour ,
issue with the py scripts , out of the box :

`python3 simple_solar_system.py 
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 58, in get_projection_class
    return projection_registry.get_projection_class(projection)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 25, in get_projection_class
    return self._all_projection_types[name]
KeyError: '3d'
`
thank's for help
Regards

raspberry pi
python3 -c 'import matplotlib; print(matplotlib.__version__)'
3.1.2

**Comment by stephengruppetta** [comment]
I'm guessing this is some issue with your Matplotlib installation

**Comment by picpic020960** [comment]
OK ; better with 3.2.2
but an other issue 


`python3 simple_solar_system.py 
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "simple_solar_system.py", line 25, in <module>
    solar_system.update_all()
  File "/home/pi/Downloads/simulation-3d-solar-system-in-python-using-matplotlib-main/solar_system_3d.py", line 34, in update_all
    body.draw()
  File "/home/pi/Downloads/simulation-3d-solar-system-in-python-using-matplotlib-main/solar_system_3d.py", line 90, in draw
    color=self.colour
  File "/home/pi/.local/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 1421, in plot
    zs = np.broadcast_to(zs, len(xs))
TypeError: object of type 'float' has no len()
`


on raspberry the better version of numpy is 1.21.6 with pip install.
exists workaround ?

**Comment by stephengruppetta** [comment]
Sorry had missed this comment. I'm not familiar with what's available on raspberry and I'm guessing this is as you suggest and issue with the numpy version. I'll need to look into what's causing the error further but it's hard since it's version dependent
